// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw_rcc3sYzLIq7J9ehnXPOzsqUvKNXZfY',
    appId: '1:1022426589843:web:39bc42726ced4176d43b66',
    messagingSenderId: '1022426589843',
    projectId: 'login-page-aaa0c',
    authDomain: 'login-page-aaa0c.firebaseapp.com',
    storageBucket: 'login-page-aaa0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgH57V9EndmhafrMDW2m6OXmevoEvha4w',
    appId: '1:1022426589843:android:cf88b8c91297bcf2d43b66',
    messagingSenderId: '1022426589843',
    projectId: 'login-page-aaa0c',
    storageBucket: 'login-page-aaa0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYNcyePeX5v_nrTJ-V4Kc4wisijMJyu9o',
    appId: '1:1022426589843:ios:128cc7ca2a6b7f2cd43b66',
    messagingSenderId: '1022426589843',
    projectId: 'login-page-aaa0c',
    storageBucket: 'login-page-aaa0c.appspot.com',
    iosBundleId: 'com.example.authenticationDemo',
  );

  static fromMap(Map<String, String> map) {}
}
